services:
  rec_hmi:
    build:
      context: .
    image: rec_hmi:latest
    container_name: rec_hmi

    network_mode: host
    privileged: true
    shm_size: 512mb
    tty: true
    stdin_open: true

    environment:
      DISPLAY: ${DISPLAY:-:0}
      QT_X11_NO_MITSHM: "1"
      LOCAL_IP: ${LOCAL_IP:-169.254.12.10}

    volumes:
      - ./:/root/lra_ws
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
